title: 'Sherry\'s Blog'
description: '时不时更新我的新收获'
keyword: '博客, 前端, 前端开发,雪莉'
url: '' # your host
baseurl: ''

# 导航
nav:
  首页: '//sherry.cf/'
  博客: '/'
  分类: '/tags.html'
  雪莉邮箱: '//sherry.cf/mail'
  雪莉音乐: '//sherry.cf/music'
  留言板: '//pls.gearhostpreview.com/leave-a-message/'

# Footer
footer:
  since: 2016

# 个人信息
author: 'Sherry'
nickname: 'Sherry'
bio: '前端开发者，学生'
avatar: 'https://avatars0.githubusercontent.com/u/18429499?s=200'

# Search
search: true

# 夜间模式
nightMode: false

# Comments 评论功能
comments:
  disqus: false
  disqus_url: 'https://liaokeyu.disqus.com/embed.js'

# MathJax 公式支持 by Ray-Eldath
mathjax: false

# Share
social-share: true
social-share-items: ['wechat', 'weibo', 'douban', 'qq', 'qzone']

# 主题
theme-color: 'pink'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'food'

# 配置社交网站
sns:
  email: 'mailto:i@sherry.cf'
  github: '//github.com/sherryme'
  douban: '//douban.com/people/jd_'

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# RSS
RSS: false

# Permalink
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:year/:month/:day/:title.html

# Plugins
plugins: [jekyll-paginate]
